# Algebra Relacional

Conceptos importantes:

‚Ä¢ Tablas -> relaci√≥n
‚Ä¢ Columna -> atributo
‚Ä¢ Fila -> tupla
‚Ä¢ Esquema -> conjunto de relaciones y sus atributos
‚Ä¢ Instancia -> conjunto de tuplas de una instancia


EL algwebra relacional es el lengujae te√≥ritrico de BDD, donde estudiaremos la **selecci√≥n, proyecci√≥n y uni√≥n** de tablas.

Tenemos un conujunto de operadores que toman como input tablas y devuelven tablas

## Operadores

### Selecci√≥n

La selecci√≥n es un operador unario que toma una tabla y devuelve una tabla con las tuplas que cumplen una condici√≥n.

La selecci√≥n se denota con el s√≠mbolo sigma (œÉ) y se define como:

œÉ<sub>condici√≥n</sub>(R)

Donde R es la tabla y condici√≥n es una expresi√≥n l√≥gica que se eval√∫a para cada tupla de la tabla.

### Proyecci√≥n

La proyecci√≥n es un operador unario que toma una tabla y devuelve una tabla con las columnas que se le indiquen.

La proyecci√≥n se denota con el s√≠mbolo pi (œÄ) y se define como:

œÄ<sub>columnas</sub>(R)

Donde R es la tabla y columnas es una lista de atributos de la tabla.

### Uni√≥n

La uni√≥n es un operador binario que toma dos tablas y devuelve una tabla con la uni√≥n de las tuplas de ambas tablas.

La uni√≥n se denota con el s√≠mbolo U y se define como:

R U S

Donde R y S son las tablas.

## Sobre la Proyecci√≥n œÄ

**Observaci√≥n**: La relaci√≥n es un **conjunto** de tuplas. Entonces no hay duplicados entre las filas de el resultado entregado por una proyecci√≥n. (En las filas de la tabla resultante no hay tuplas duplicadas)

## Sobre la Selecci√≥n œÉ

Las condiciones que operan pueden ser:

'==', '>', '<', '>=', '<=', '!='

y se pueden combinar con los operadores l√≥gicos 'and', 'or'.


**Nota** Aplicamos la poryecci√≥n cuando nos piden atributos (**columnas**) especificas, cuando hablamos de todas las columnas podmeos aplicar otras operaciones. (como la selecci√≥n)

## Sobre la Uni√≥n U

Sean R_{1}, R_{2}  relaciones con la misma cantidad de atributos y
del mismo tipo, entonces R_{1} U R_{2}es una nueva relaci√≥n que
contiene la uni√≥n de las tuplas de R_{1} y R_{2}

**NOta** Es importante saber que luego de unir ambas tablas con sus tuplas, 1 no se van a repitir valores en la tabla resultante y dos se va a quedar todo junto en una sola tabla,con un soo nombre de atributo. Por ejemplo: Liste el **nombre** de todos los actores y directores. En este caso se unen las tablas de actores y directores y se proyecta el nombre de ambos atributos **actores.nombre** y **directores.director** en un solo atributo **nombre**.

## Renombrando atrbiutos

Para cambiar el nombre de los atributos de una instancia se usa el operador œÅ (rho).

![image](img/rho_atributos.png)


## Renombrando relaciones (tablas)

Para cambiar el nombre de una relaci√≥n se usa el operador œÅ (rho).

![image](img/rho_tablas.png)

## Producto Cruz y Join

Al usar producto cruz juntamos todas las tuplas de una tabla con todas las tuplas de otra tabla.

El join es similar al producto cruz, pero se hace con una condici√≥n. Por ejemplo, si tenemos dos tablas A y B, podemos hacer un join de A y B con la condici√≥n A.id = B.id. En este caso, se juntar√°n las tuplas de A y B que tengan el mismo id.

![image](img/join.png)

## Join en resumen

En resumen join es igual a producto cruz, pero con una condici√≥n.

R1 JOIN condici√≥n R2 = œÉ<sub>condici√≥n</sub>(R1 x R2)

## Iteraci√≥n de Joins(join de join de join...)

Si tenemos m√°s de dos tablas, podemos hacer un join de join de join... de la siguiente manera:

R1 JOIN condici√≥n1 R2 JOIN condici√≥n2 R3 = (R1 JOIN condici√≥n1 R2) JOIN condici√≥n2 R3 = œÉ<sub>condici√≥n2</sub>(œÉ<sub>condici√≥n1</sub>(R1 x R2) x R3)

Ejemplo:

Liste cada actor junto a todas las pel√≠culas en las que ha actuado. (utilizamos proyeccion y dos joins)

œÄ<sub>actor.nombre, pelicula.nombre</sub>(actuo_en JOIN
<sub>peliculas.id=actuo_en.id_pelicula</sub> peliculas JOIN<sub>actores.id=actuo_en.id_actor</sub> actores)

## JOin natural

Definir las relaciones 
ùëÖ
1
R 
1
‚Äã
  y 
ùëÖ
2
R 
2
‚Äã
 :
En este caso, las dos relaciones son las tablas de "actores" y "directores". Ambos tienen los mismos atributos: "nombre" y "edad".

Relaci√≥n 
ùëÖ
1
R 
1
‚Äã
  (actores):

Leonardo DiCaprio, 41
Matthew McConaughey, 46
Daniel Radcliffe, 27
Clint Eastwood, 192
Relaci√≥n 
ùëÖ
2
R 
2
‚Äã
  (directores):

Clint Eastwood, 192
Christopher Nolan, 50
Martin Scorsese, 78
Wes Anderson, 51
2. Aplicar el operador de uni√≥n natural 
‚ãà
‚ãà:
De acuerdo con la definici√≥n de la intersecci√≥n en la primera imagen, el primer paso es aplicar un join natural entre las dos relaciones sobre los atributos comunes (en este caso, "nombre" y "edad"). Esto significa que seleccionamos los registros que coinciden en ambos atributos.

3. Identificar las tuplas comunes:
Al hacer el join natural, observamos que la √∫nica fila en com√∫n entre las dos tablas es la correspondiente a Clint Eastwood con la edad 192. Esta es la √∫nica coincidencia, ya que tanto el "nombre" como la "edad" son id√©nticos en ambas tablas.

4. Proyectar el resultado:
Una vez identificada la tupla que satisface el join natural, realizamos una proyecci√≥n (
ùúã
œÄ) sobre los atributos "nombre" y "edad", lo que nos lleva al resultado final.

5. Resultado final:
El resultado de la intersecci√≥n es una tabla con los atributos de "nombre" y "edad", que contiene:

Clint Eastwood, 192
Esto corresponde a la √∫ltima tabla de la segunda imagen, que muestra el resultado de la intersecci√≥n.

Resumen:
Aplicamos la intersecci√≥n sobre las relaciones "actores" y "directores" utilizando un join natural y proyectando los atributos comunes, lo que nos lleva al resultado final: Clint Eastwood, 192.

## Diferencia

La diferencia entre dos tablas es una operaci√≥n que devuelve las tuplas de la primera tabla que no est√°n presentes en la segunda tabla.

Ambas tablas deben tener la misma cantidad de atributos y del mismo tipo. (Los atributos son las columnas de la tabla y las filas son las tuplas) 

Si en R2 hay cosas que  no estan en R1, simpemnete no se agregan

En resuemn, en la diferencia quedan klas tuplas de la primera tabla que no estan en la segunda tabla. y las cosas de la segunda tala que no esten en la primera tabla simplemente no se agregan.